import asyncio
from telethon import TelegramClient, events
from telethon.sessions import StringSession
from telethon.errors import PhoneNumberInvalidError, PhoneCodeInvalidError, SessionPasswordNeededError
from telegram.ext import Application, CommandHandler, ContextTypes

import os

# === Конфигурация ===
API_ID = int(os.environ.get("API_ID"))
API_HASH = os.environ.get("API_HASH"))
BOT_TOKEN = os.environ.get("BOT_TOKEN"))

# Храним данные пользователей (в памяти, не в БД)
user_sessions = {}
user_keywords = {}


# === Шаг 1. /connect ===
async def connect(update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Введите номер телефона в формате +79991234567:")
    context.user_data["awaiting_phone"] = True


# === Шаг 2. получение номера ===
async def handle_message(update, context):
    user_id = update.effective_user.id
    text = update.message.text.strip()

    # Если ждем номер
    if context.user_data.get("awaiting_phone"):
        phone = text
        try:
            session = StringSession()
            client = TelegramClient(session, API_ID, API_HASH)
            await client.connect()
            await client.send_code_request(phone)
            user_sessions[user_id] = {"client": client, "session": session, "phone": phone}
            context.user_data["awaiting_phone"] = False
            context.user_data["awaiting_code"] = True
            await update.message.reply_text("Код отправлен. Введите код, пришедший в Telegram:")
        except PhoneNumberInvalidError:
            await update.message.reply_text("❌ Неверный номер. Попробуйте снова.")
        return

    # Если ждем код
    if context.user_data.get("awaiting_code"):
        code = text
        data = user_sessions.get(user_id)
        client = data["client"]
        phone = data["phone"]
        try:
            await client.sign_in(phone=phone, code=code)
            context.user_data["awaiting_code"] = False
            await update.message.reply_text("✅ Авторизация успешна!\nТеперь введите ключевые слова через запятую:")
            context.user_data["awaiting_keywords"] = True
        except PhoneCodeInvalidError:
            await update.message.reply_text("❌ Неверный код.")
        except SessionPasswordNeededError:
            await update.message.reply_text("У вас включена двухэтапная аутентификация. Этот бот её не поддерживает.")
        return

    # Если ждем ключевые слова
    if context.user_data.get("awaiting_keywords"):
        kws = [w.strip().lower() for w in text.split(",")]
        user_keywords[user_id] = kws
        context.user_data["awaiting_keywords"] = False
        await update.message.reply_text(f"🔍 Ключевые слова сохранены: {', '.join(kws)}\nБот теперь читает ваши чаты.")
        asyncio.create_task(start_monitoring(user_id))
        return


# === Шаг 3. Мониторинг ===
async def start_monitoring(user_id):
    data = user_sessions[user_id]
    client = data["client"]
    keywords = user_keywords.get(user_id, [])

    @client.on(events.NewMessage(incoming=True))
    async def handler(event):
        text = event.message.message.lower()
        if any(k in text for k in keywords):
            chat = await event.get_chat()
            await client.send_message("me", f"🛰 Найдено совпадение:\nЧат: {chat.title or chat.username}\n\n{text}")

    await client.run_until_disconnected()


# === Запуск бота ===
async def main():
    app = Application.builder().token(BOT_TOKEN).build()
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start", connect))
    app.add_handler(CommandHandler("help", connect))
    app.add_handler(CommandHandler("monitor", connect))
    app.add_handler(CommandHandler("connect", connect))
    app.add_handler(CommandHandler("start